### PR TITLE
Fix de-normalization error in EarthAtm class

### PR DESCRIPTION
**Pull request by ConnorSponsler**
Fixes incorrect de-normalization of relative radius in order to correctly return the current height above the surface of Earth along the track.

### CODE REVIEW

**Comment by cnweaver** [comment]
It seems like it would be simpler to compute `h=r-radius`? (Likewise, instead of `rel_r > radius/earth_with_atm_radius`, just `r > radius`?)

**Comment by ConnorSponsler** [comment]
image

 Here is a plot of the varying densities compared to the expected exponential profile at a coszen = -1

**Review by cnweaver — APPROVED** [review]
Looks good to me.

**Comment by ConnorSponsler** [comment]
I changed the condition back to match with the other conditionals around this part of the code which seem to be that way to make the case and argument of the interpolation function more intuitive. I can propose a version where they are all the simpler case.

**Comment by cnweaver** [comment]
I think that would be great, unless @arguelles objects; in the original version of the code I had to squint a lot to figure out what any of the conditions did.

**Comment by ConnorSponsler** [comment]
I kept it that way to match with the conditionals around it which are written that way to work more intuitively with the "x_radius_min" and max. It seems as if in the past it was written in prioritizing readability, but don't know what we would want to prioritize here.

**Comment by ConnorSponsler** [comment]
So the current version I am proposing just replaces every comparison between "rel_r" and "radius/earth_with_atm_radius" with the same comparison between "r" and "radius"

**Review by arguelles — COMMENTED** [review]
Looks good.

**Pull request merged**
